### ISSUE TITLE
Unable to get content that works in cURL (does not support HTTP/2)

### ISSUE THREAD

**Issue by forthrin** [ruby/net-http#136]
`net/http` waits forever when connecting to certain sites, ie.

```
require 'net/http'
header = { 'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:112.0) Gecko/20100101 Firefox/112.0' }
http = Net::HTTP.start('www.tripadvisor.com', 443, use_ssl: true)
response = http.get('/', header)
^C
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/3.2.0/net/protocol.rb:229:in `wait_readable': Interrupt
```

Whereas `cURL` returns the site content without hesitance.

```
$ time curl -s -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:112.0) Gecko/20100101 Firefox/112.0" 'https://www.tripadvisor.com/' | wc -c
  372481
0m0.815s
```

Both methods seem to be sending the same HTTP headers (`Accept`, `Accept-Encoding`, `User-Agent`).

Is this a bug in `net/http`?

Is there a temporary and/or permanent workaround to make the request work in `net/http`?

**Comment by forthrin** [comment]
Bump

**Comment by HoneyryderChuck** [comment]
@forthrin seems that the server is timing out when the request is performed with HTTP/1.1 . And your curl example is probably succeeding with HTTP/2 (or 3?). I can reproduce it with [httpx](https://honeyryderchuck.gitlab.io/httpx/):

```ruby
require "httpx"
header = { 'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:112.0) Gecko/20100101 Firefox/112.0' }
# uses http/2 by default, via alpn negotiation
HTTPX.get("https://www.tripadvisor.com/", headers: header) => #<Response:3200 HTTP/2.0 @status=200...
# forces alpn negotiation to http/1.1
HTTPX.get("https://www.tripadvisor.com/", headers: header, ssl: { alpn_protocols: %w[http/1.1]}) #=> #<HTTPX::ErrorResponse:0x000000010c5c4b50
 @error=#<HTTPX::TimeoutError: timed out while waiting on select>...
```

**Comment by forthrin** [comment]
@HoneyryderChuck: Thanks for pointing me in this direction. Before I decide on a possible switch:

1. Doesn't `net/http` support HTTP/2 at all? Is it stale, bordering abandonware?
1. Is `httpx` the most up-to-date, feature-complete and user-friendly of [HTTP libraries](https://www.scrapingbee.com/blog/best-ruby-http-clients/)?
1. Is the "cURL to httpx" functionality on the landing page available from CLI or Ruby?
1. Amusingly, `httpx` hung too, but for resolving [100k+ hosts entries](https://github.com/StevenBlack/hosts). I solved this by patching [resolv](https://github.com/ruby/resolv/blob/master/lib/resolv.rb#L198) with `next if !addr || addr.start_with?('0')`. I guess I should report this to the author, as this doesn't seem configurable.

**Comment by HoneyryderChuck** [comment]
1. I wouldn't call net-http abandonware, it's actively maintained and relied upon by the community. That being said, it's mostly in "maintenance mode" , and there's no one really making sure it supports the most recent versions of the protocol.
2. I'm the maintainer, so my answer will be biased. Yes it's the most feature complete option, and actively maintained. However, read the wiki and judge it by yourself.
3. Not yet, but it could be. It's literally an optparse driven script translated to js via opal.
4. Feel free to report the bug with a reproduction in the repo, I'll see it gets fixed.

**Comment by forthrin** [comment]
`httpx` seems to sport a terse and intuitive syntax for common feats, which is what I'm always looking for. I'll try it and let you know about any issues. I replaced the article reference and suggested a [patch](https://github.com/ruby/resolv/issues/38).

**Comment by forthrin** [comment]
@HoneyryderChuck: Looks more than good for my use. Some questions:

1. How does one fine-tune verbosity, ie. print a selection of some of the below?
- the URL about to be fetched
- redirect notices
- the full response header (and raise an exception) if an error occured (ie. not 200 or 3xx)?
- milliseconds the request took
1. Is there (or could be) a plugin for local caching (mirror tree)?(Where the user, not the server, controls expiration!)
1. Is there (or could be) a callback for the user to render a progress bar?

**Comment by HoneyryderChuck** [comment]
@forthrin in order not to prolong this thread, feel free to re-ask this either in the httpx repo, or in the github discussions space of its github mirror repo. happy to get those answered there.

**Comment by forthrin** [comment]
I thought the exact same thing, and I've posted an issue you the Github repo, as I don't have a Gitlab account. Thanks!
