### ISSUE TITLE
Why do the tags point to the wrong versions of files?

### ISSUE THREAD

**Issue by contentfree** [ruby/net-http#152]
The v0.1.0 tag for the gemspec is not the gemspec that was at v0.1.0 and breaks the ability to install older versions of the gem (that supported Ruby 2.5, for example). Yes, 2.5 has reached EOL but sometimes people don't have the resources to upgrade yet.

**Comment by contentfree** [comment]
Maybe I'm just reading the history incorrectly. Was the v0.1.0 tag _really_ created after dropping supported for Ruby 2.5?

**Comment by hsbt** [comment]
Unfortunately, while Ruby 2.5-2.7 is migration period. So, we organized gem releases after Ruby 2.7 or later.
