### ISSUE TITLE
Release 0.2.1 with openssl feature checks

### ISSUE THREAD

**Issue by headius** [ruby/net-http#54]
Hello from JRuby!

We have been testing JRuby master (9.4) with Rails 7 for the past couple weeks using 0.2.1.pre1 and the openssl feature checks appear to be functioning properly.

I am requesting that we do a formal release, so that JRuby 9.4 and Rails 7 users do not have to request --pre gems.

**Comment by hsbt** [comment]
Ah, I mistaken to release 0.2.2 at https://github.com/ruby/net-http/commit/992d07cb41a2a6d9b477a7c8dab1ee65a773c186.

I should only cut the `.pre` in the next time 🙇

**Comment by headius** [comment]
No worries about this and the other missed version. We are very happy to have these released!
